### ISSUE TITLE
Error: Barcode file for chrom {0} doesn't exist!!!!".format(chrm)

### ISSUE THREAD

**Issue by anderswe** [simoncchu/BarcodeMate#2]
Hi Simon,

Thank you for BarcodeMate, excited to use it in preparation for xTea.

I am running the following line, in hopes of creating a barcode-indexed ```.bam``` from a position-sorted ```.bam``` which was produced from 10X Linked-Reads FASTQs after a call to ```longranger align```:

```
python /hpf/anders/clones/BarcodeMate/x_toolbox.py -C \
-b longranger_outs/sample123/outs/possorted_bam.bam \
-o barcodemate_outs/sample123_barcode_indexed.bam \
-p ./tmp \
-n 4
```

Which triggers the following error:
```
Traceback (most recent call last):
  File "/hpf/anders/clones/BarcodeMate/x_toolbox.py", line 7, in <module>
    from x_converter import *
  File "/hpf/anders/clones/BarcodeMate/x_converter.py", line 88
    print "Error: Barcode file for chrom {0} doesn't exist!!!!".format(chrm)
                                                              ^
SyntaxError: invalid syntax
```

I would greatly appreciate your advice about how to go about fixing this – thank you!

**Comment by simoncchu** [comment]
@anderswe sorry for the late reply. Somehow this is not notified in my major email...

The code was implemented with python2 not python3. Could you try with python2?
